### ISSUE TITLE
Msg Key mismatch

### ISSUE THREAD

**Issue by butthx** [tgsnake/core#1]
Some raw functions can escape sha256 msg key checking. But some raw functions will experience msg key mismatch. It will always happen even if the websocket is restarted. I've been trying to figure out what to do when I get the error, but to no avail. Maybe anyone can help me to fix it.

[Error Reference](https://github.com/tgsnake/core/blob/0d834d0c72d5231d2cebfbb466ca8ea8bc3fa094/src/crypto/Mtproto.ts#L107)

**Comment by hypernova7** [comment]
@butthx Have you tried this, as you are currently creating a 2D buffer and it shouldn't be that way as far as I know.

```js
new SecurityCheckMismatch(
  msgKey.equals(sha256(Buffer.concat([...authKey.slice(96, 96 + 32), ...data.buffer])).slice(8, 24)),
  'Provided msg key is not equal with expected one'
);
```

**Comment by butthx** [comment]
@hypernova7 Yeah, i have tried. It still doesn't work, but it throw new error TypeError [ERR_INVALID_ARG_TYPE]: The "list[0]" argument must be an instance of Buffer or Uint8Array. Received type number (65).

**Comment by butthx** [comment]
It's look the `crypto/Mtproto.ts` is broken, idk where the line of broken code, because i'm testing to get the hex bytes of `packet`, `auth_key`, `session_id` and `auth_key_id` from `pyrogram` it still going to be crash. I'll try to find out a way around this.

**Comment by butthx** [comment]
This issue has been fixed!
