### ISSUE TITLE
Unhandled promise rejections on disconnection

### ISSUE THREAD

**Issue by SAPikachu** [tgsnake/core#4]
Hi, I am using this library as update listener, I noticed that around every hour the connection to Telegram server will be closed and there will be 2 unhandled promise rejection:

1.
```
Error: WebSocket connection closed when reading data
    at Socket.read (/app/node_modules/@tgsnake/core/lib/src/connection/WebSocket.js:238:19)
    at TCPFull.recv (/app/node_modules/@tgsnake/core/lib/src/connection/TCP/tcp.js:81:25)
    at TCPFull.recv (/app/node_modules/@tgsnake/core/lib/src/connection/TCP/TCPFull.js:44:23)
    at Connection.recv (/app/node_modules/@tgsnake/core/lib/src/connection/connection.js:132:16)
    at Session._networkWorker (/app/node_modules/@tgsnake/core/lib/src/session/Session.js:278:34)
```

2.
```
Error: Client is already disconnected to server.
    at Connection.close (/app/node_modules/@tgsnake/core/lib/src/connection/connection.js:118:19)
    at Session.stop (/app/node_modules/@tgsnake/core/lib/src/session/Session.js:316:36)
```

The session will restore after a few seconds if I set up global handler to ignore them. It would be great if this can be handled inside the library without triggering global handler. Thanks!

**Comment by butthx** [comment]
Hi, thank you for reporting this issue. In future versions I will try to add a function for auto reconnect. I'll let you know when it's finished.

**Comment by SAPikachu** [comment]
Thanks! Just for your information, it already can auto-reconnect if we handle these 2 failed promise.

**Comment by SAPikachu** [comment]
Log from our server:

![image](https://github.com/tgsnake/core/assets/653824/6cf47d33-6c4b-4f86-a07c-1f2cd71bda5f)

**Comment by butthx** [comment]
Hi, I have added a function to this library to automatically reconnect, can you test it before I push to npm to make sure that the code I added is working.

```bash
git clone https://github.com/tgsnake/core
yarn install
yarn build
```

In the local build there will be a 'lib' folder available, use that as a test.
```js
const { Client } = require('./lib/src')
```

**Comment by SAPikachu** [comment]
Thank you very much for the quick response! I will set it up a bit later today and see whether it is fixed.

**Comment by SAPikachu** [comment]
Seems it still fails:
```
Starting Telegram listener
(@tgsnake/core) info - [100] Using version: 1.11.0 - Stable 4/5/2024 12:0:34.883
(@tgsnake/core) info - [69] Session initialized: Layer 179 4/5/2024 12:0:36.54
(@tgsnake/core) info - [70] Device: Linux - 1.11.0 4/5/2024 12:0:36.54
(@tgsnake/core) info - [71] System: 6.5.0-1019-azure (EN) 4/5/2024 12:0:36.54
(@tgsnake/core) info - [135] Getting Update State 4/5/2024 12:0:36.54
(@tgsnake/core) info - [72] Session Started 4/5/2024 12:0:36.54
Telegram bot ID: 6523390852
Listening on http://0.0.0.0:3000
(@tgsnake/core) info - [136] Reconnecting to Telegram Server. 4/5/2024 13:17:9.578
/home/sapikachu/Sync/devel/tgsnake-core/lib/src/connection/WebSocket.js:238
            throw new index_js_1.WSError.ReadClosed();
                  ^
ReadClosed [Error]: WebSocket connection closed when reading data
    at Socket.read (/home/sapikachu/Sync/devel/tgsnake-core/lib/src/connection/WebSocket.js:238:19) {
  description: 'This happen when suddenly the connection between the websocket client and the server is lost when fetching data updates from the server.'
}
```

**Comment by butthx** [comment]
> Seems it still fails:
> 
> ```
> Starting Telegram listener
> (@tgsnake/core) info - [100] Using version: 1.11.0 - Stable 4/5/2024 12:0:34.883
> (@tgsnake/core) info - [69] Session initialized: Layer 179 4/5/2024 12:0:36.54
> (@tgsnake/core) info - [70] Device: Linux - 1.11.0 4/5/2024 12:0:36.54
> (@tgsnake/core) info - [71] System: 6.5.0-1019-azure (EN) 4/5/2024 12:0:36.54
> (@tgsnake/core) info - [135] Getting Update State 4/5/2024 12:0:36.54
> (@tgsnake/core) info - [72] Session Started 4/5/2024 12:0:36.54
> Telegram bot ID: 6523390852
> Listening on http://0.0.0.0:3000
> (@tgsnake/core) info - [136] Reconnecting to Telegram Server. 4/5/2024 13:17:9.578
> /home/sapikachu/Sync/devel/tgsnake-core/lib/src/connection/WebSocket.js:238
>             throw new index_js_1.WSError.ReadClosed();
>                   ^
> ReadClosed [Error]: WebSocket connection closed when reading data
>     at Socket.read (/home/sapikachu/Sync/devel/tgsnake-core/lib/src/connection/WebSocket.js:238:19) {
>   description: 'This happen when suddenly the connection between the websocket client and the server is lost when fetching data updates from the server.'
> }
> ```

Hi Thank you for testing, are there any more logs below like [72]?

**Comment by SAPikachu** [comment]
No, my program exited after the last line.

**Comment by SAPikachu** [comment]
FYI I tested in my local system and it doesn't add unhandled promise handler, if needed I can add that to simulate my server environment.

**Comment by butthx** [comment]
> No, my program exited after the last line.

Hmm, that weird. Based on the first log, the error appears from Session._networkWorker. The catch function should have been called with log 136 appearing.

I will investigate this further.

**Comment by SAPikachu** [comment]
I added unhandled promise handler to test and now the log looks like this:
```
Starting Telegram listener
(@tgsnake/core) info - [100] Using version: 1.11.0 - Stable 4/5/2024 14:50:10.145
(@tgsnake/core) info - [69] Session initialized: Layer 179 4/5/2024 14:50:11.524
(@tgsnake/core) info - [70] Device: Linux - 1.11.0 4/5/2024 14:50:11.524
(@tgsnake/core) info - [71] System: 6.5.0-1019-azure (EN) 4/5/2024 14:50:11.524
(@tgsnake/core) info - [135] Getting Update State 4/5/2024 14:50:11.524
(@tgsnake/core) info - [72] Session Started 4/5/2024 14:50:11.524
Telegram bot ID: 6523390852
Listening on http://0.0.0.0:3000
(@tgsnake/core) info - [136] Reconnecting to Telegram Server. 4/5/2024 16:20:5.920
Unhandled rejection: {
  _: 'ReadClosed',
  message: 'WebSocket connection closed when reading data',
  description: 'This happen when suddenly the connection between the websocket client and the server is lost when fetching data updates from the server.'
}
(@tgsnake/core) info - [69] Session initialized: Layer 179 4/5/2024 16:20:7.44
(@tgsnake/core) info - [70] Device: Linux - 1.11.0 4/5/2024 16:20:7.44
(@tgsnake/core) info - [71] System: 6.5.0-1019-azure (EN) 4/5/2024 16:20:7.44
(@tgsnake/core) info - [135] Getting Update State 4/5/2024 16:20:7.44
(@tgsnake/core) info - [72] Session Started 4/5/2024 16:20:7.44
```

**Comment by SAPikachu** [comment]
I found that there is a small window that the promise was not be linked with `.catch`, with this patch it seems no more unhandled promise is happening:

```diff
diff --git a/src/Timeout.ts b/src/Timeout.ts
index 4677dcd..cd1c92e 100644
--- a/src/Timeout.ts
+++ b/src/Timeout.ts
@@ -27,9 +27,10 @@ export class Timeout {
    * @param {Number} time - Max time execution for function.
    * @param {Function} onTimeout - When function running more than time, this function will be called.
    */
-  run(task: Promise<any>, time: number, onTimeout?: OnTimeout) {
-    if (time === Infinity) return task;
+  run(_task: Promise<any> | (() => Promise<any>), time: number, onTimeout?: OnTimeout) {
+    if (time === Infinity) return typeof _task === 'function' ? _task() : _task;
     return new Promise((res, rej) => {
+      const task = typeof _task === 'function' ? _task() : _task;
       let index = this._task.length;
       let timeout = setTimeout(() => {
         if (onTimeout) {
@@ -37,9 +38,11 @@ export class Timeout {
         } else {
           rej(new TimeoutError(time));
         }
-        task.finally(() => {
-          return 'Running timeout';
-        });
+        task
+          .finally(() => {
+            return 'Running timeout';
+          })
+          .catch(() => {});
       }, time);
       this._task.push(timeout);
       task
diff --git a/src/connection/TCP/tcp.ts b/src/connection/TCP/tcp.ts
index 6e27502..2baca1b 100644
--- a/src/connection/TCP/tcp.ts
+++ b/src/connection/TCP/tcp.ts
@@ -77,7 +77,7 @@ export class TCP {
     let data = Buffer.alloc(0);
     while (data.length < length) {
       let chunk = await this._task.run(
-        this._socks.read(length - data.length),
+        () => this._socks.read(length - data.length),
         this._socks.timeout,
         () => {},
       );
```

**Comment by butthx** [comment]
Thank you, I will try to add it to the source code.

**Comment by butthx** [comment]
I just committed and added a maximum reconnect retries system and added a `.catch` to the task in the Timeout class.

```diff
diff --git a/src/Timeout.ts b/src/Timeout.ts
index 4677dcdc..fbecc637 100644
--- a/src/Timeout.ts
+++ b/src/Timeout.ts
@@ -37,7 +37,7 @@ export class Timeout {
         } else {
           rej(new TimeoutError(time));
         }
-        task.finally(() => {
+        task.catch(rej).finally(() => {
           return 'Running timeout';
         });
       }, time);
```

We can't ignore error using catch in the Timeout class but we can do promise reject there. So when a task errors, we can do a try-catch in the function that calls the method from the Timeout class.

Now, should be try-catch in `_networkWorker` working as expected.

**Comment by SAPikachu** [comment]
Thanks! I am now testing the latest commit locally.

**Comment by SAPikachu** [comment]
Works mostly OK, but I see 2 `[136] Reconnecting to Telegram Server.` lines output to console when reconnecting happens. Not sure whether it matters. Thanks for the fix!

**Comment by butthx** [comment]
_Thank you for reporting and testing. I will close this issue and mark it as solved. I will push to npm later along with other bug fixes. If in the latest version this bug appears again, you can open this issue again._

# Summary
- The connection to the Telegram server is interrupted after some time.
- When the connection is interrupted, the client read bytes and a `ReadClosed` error appears.
- When `ReadClosed` error appears, `networkWorker` cannot handle it, causing the app to crash.
- This issue affected to oldest version of `@tgsnake/core` and `tgsnake` version `3.0.0` ~ `3.2.0`

## Solution 
- Update to `tgsnake` version `3.3.0` or `@tgsnake/core` to `1.11.0`
- Building from local source 
```bash
git clone https://github.com/tgsnake/core
yarn install
yarn build
```
```js
const { Client } = require('./lib/src')
```
