### ISSUE TITLE
No docs bro?

### ISSUE THREAD

**Issue by Jobians** [tgsnake/core#6]

**Comment by butthx** [comment]
You can look a Deno version documentation 

[https://deno.land/x/tgsnake_core@1.10.10/src/index.ts](https://deno.land/x/tgsnake_core@1.10.10/src/index.ts)

**Comment by Jobians** [comment]
> You can look a Deno version documentation
> 
> https://deno.land/x/tgsnake_core@1.10.10/src/index.ts

Try
https://typedoc.org/

**Comment by butthx** [comment]
> > You can look a Deno version documentation
> > https://deno.land/x/tgsnake_core@1.10.10/src/index.ts
> 
> Try https://typedoc.org/

I tried it, but it doesn't support Deno source code, and I tried the deno doc with github pages and it crashed (404 even though the page is available) so I withdrew it temporarily.

**Comment by butthx** [comment]
https://tgsnake.github.io/core/

Idk if there is some configuration wrong with gh-pages. It's always show 404

**Comment by Jobians** [comment]
> https://tgsnake.github.io/core/
> 
> Idk if there is some configuration wrong with gh-pages. It's always show 404

Ok bro but in the readme try to add how to handle some updates like message

**Comment by butthx** [comment]
Ok, soon. But in simple terms, you can use tgsnake.

```js
// tgsnake 3.2.0
client.on('message', (ctx,next) => {
  ctx.message.reply('Hello')
  return next() // If you want the handler to stop here, do not call next.
  // you can access tgsnake/core client via client.core
})
```

In tgsnake/core it's also possible, but it's a little complicated because you have to handle Raw.Updates then do filtering.

```js
client.addHandler((update) => {
  if(update instanceof Raw.Updates){
    for(let up in update.updates){
      if(up instanceof Raw.updates.UpdateNewChannelMessage){
        // do something 
      }
    }
  }
})
```

**Comment by Jobians** [comment]
Ok thanks but include examples folder and add some examples when you have free time.

Thanks brother

**Comment by butthx** [comment]
Ok, if you need help you can chat in the group or privately. I might not respond if it's nighttime in my area (GMT +7), but I will respond the next day.
