### ISSUE TITLE
not working on my corei5 imac

### ISSUE THREAD

**Issue by Jobians** [tgsnake/core#8]
An error occurred: {
  _: 'ClientDisconnected',
  message: "Can't send request to telegram when client is unconnected.",
  description: 'The provided telegram client is unconnected, make sure to start the telegram client firsy before sending request.'
}

**Comment by butthx** [comment]
Hi, can you provide more details? like when the error occurs.. you can also include logs.

**Comment by Jobians** [comment]
info: Starting Telegram client...
(@tgsnake/core) info - [100] Using version: 1.13.7 - Stable 23/8/2024 13:47:31.234
(@tgsnake/core) debug - [11] Start creating a new auth key on DC2 23/8/2024 13:47:31.239
(@tgsnake/core) debug - [1] Connecting to DC2 with TCPFull 23/8/2024 13:47:31.240

(@tgsnake/core) debug - [12] Send ResPq: -148340740479427071801747925893717100609 23/8/2024 13:47:31.395
(@tgsnake/core) debug - [2] Sending 40 bytes data. 23/8/2024 13:47:31.396
(@tgsnake/core) debug - [3] Receive 112 bytes data 23/8/2024 13:47:31.542
(@tgsnake/core) debug - [10] Reading TLObject with id: 5162463 (Raw.ResPQ) 23/8/2024 13:47:31.543
(@tgsnake/core) debug - [10] Reading TLObject with id: 1cb5c415 (Primitive.Vector) 23/8/2024 13:47:31.544
(@tgsnake/core) debug - [13] Got ResPq: 94874200826436610442714599017609958992 23/8/2024 13:47:31.544
(@tgsnake/core) debug - [14] Server public key fingerprints: 847625836280919973,-4344800451088585951,-3414540481677951611 23/8/2024 13:47:31.545
(@tgsnake/core) debug - [15] Using fingerprint: 847625836280919973 23/8/2024 13:47:31.545
(@tgsnake/core) debug - [17] Start PQ factorization: 2413468498066987043 23/8/2024 13:47:31.545
(@tgsnake/core) debug - [18] Done PQ factorization (3s): 1289234021 1872017383 23/8/2024 13:47:34.870
(@tgsnake/core) debug - [19] Length of encrypted data: 256 23/8/2024 13:47:34.873
(@tgsnake/core) debug - [20] Done encrypt data with RSA 23/8/2024 13:47:34.873
(@tgsnake/core) debug - [21] Send ReqDhParams 23/8/2024 13:47:34.874
(@tgsnake/core) debug - [2] Sending 340 bytes data. 23/8/2024 13:47:34.874
(@tgsnake/core) debug - [3] Receive 664 bytes data 23/8/2024 13:47:35.586
(@tgsnake/core) debug - [10] Reading TLObject with id: d0e8075c (Raw.ServerDhParamsOk) 23/8/2024 13:47:35.587
(@tgsnake/core) debug - [5] Decrypting 592 bytes data with AES-256-IGE 23/8/2024 13:47:35.588
(@tgsnake/core) debug - [10] Reading TLObject with id: b5890dba (Raw.ServerDhInnerData) 23/8/2024 13:47:35.602
(@tgsnake/core) debug - [22] Done decrypting answer 23/8/2024 13:47:35.607
(@tgsnake/core) debug - [23] Delta time: -29292 23/8/2024 13:47:35.609
(@tgsnake/core) debug - [4] Encrypting 336 bytes data with AES-256-IGE 23/8/2024 13:47:35.673
(@tgsnake/core) debug - [24] Length of encrypted data: 336 23/8/2024 13:47:35.678
(@tgsnake/core) debug - [25] Send SetClientDhParams 23/8/2024 13:47:35.681
(@tgsnake/core) debug - [2] Sending 396 bytes data. 23/8/2024 13:47:35.682
(@tgsnake/core) debug - [3] Receive 84 bytes data 23/8/2024 13:47:36.321
(@tgsnake/core) debug - [10] Reading TLObject with id: 3bcbf734 (Raw.DhGenOk) 23/8/2024 13:47:36.322
(@tgsnake/core) debug - [26] DH parameters check: OK 23/8/2024 13:47:36.353
(@tgsnake/core) debug - [27] gA and gB validation: OK 23/8/2024 13:47:36.353
(@tgsnake/core) debug - [28] SHA1 hash values check: OK 23/8/2024 13:47:36.353
(@tgsnake/core) debug - [29] Nonce fields check: OK 23/8/2024 13:47:36.353
(@tgsnake/core) debug - [30] Server salt: 1851499668356876784 23/8/2024 13:47:36.354
(@tgsnake/core) debug - [31] Done auth key exchange: DhGenOk 23/8/2024 13:47:36.354
(@tgsnake/core) debug - [68] Connecting to telegram server 23/8/2024 13:47:36.355
(@tgsnake/core) debug - [1] Connecting to DC2 with TCPFull 23/8/2024 13:47:36.355
(@tgsnake/core) debug - [57] Network worker started. 23/8/2024 13:47:36.487
(@tgsnake/core) debug - [50] Sending msg id 7406439414236184576 (Ping), has 28 bytes message. 23/8/2024 13:47:36.489
(@tgsnake/core) debug - [4] Encrypting 64 bytes data with AES-256-IGE 23/8/2024 13:47:36.490
(@tgsnake/core) debug - [51] Sending 88 bytes payload. 23/8/2024 13:47:36.490
(@tgsnake/core) debug - [2] Sending 88 bytes data. 23/8/2024 13:47:36.490
(@tgsnake/core) debug - [3] Receive 100 bytes data 23/8/2024 13:47:36.627
(@tgsnake/core) debug - [33] Unpacking 88 bytes packet. 23/8/2024 13:47:36.628
(@tgsnake/core) debug - [5] Decrypting 64 bytes data with AES-256-IGE 23/8/2024 13:47:36.628
(@tgsnake/core) debug - [10] Reading TLObject with id: a7eff811 (Raw.BadMsgNotification) 23/8/2024 13:47:36.629
(@tgsnake/core) debug - [34] Reveive 1 data. 23/8/2024 13:47:36.630
(@tgsnake/core) debug - [35] Setting server time: 1724416764. 23/8/2024 13:47:36.630
(@tgsnake/core) debug - [40] Got BadMsgNotification and msg id is: 7406439414236184576. 23/8/2024 13:47:36.630
(@tgsnake/core) debug - [44] Setting results of msg id 7406439414236184576 with BadMsgNotification. 23/8/2024 13:47:36.630
(@tgsnake/core) debug - [54] Got response from msg id 7406439414236184576: BadMsgNotification 23/8/2024 13:47:36.630
(@tgsnake/core) debug - [62] Invoking auth.SendCode with parameters: 0 retries, 15000ms timeout, 10000ms sleep threshold. 23/8/2024 13:47:36.631
(@tgsnake/core) error - [63] Can't sending request when client is unconnected. 23/8/2024 13:47:36.631
An error occurred: {
  _: 'ClientDisconnected',
  message: "Can't send request to telegram when client is unconnected.",
  description: 'The provided telegram client is unconnected, make sure to start the telegram client firsy before sending request.'
}

**Comment by butthx** [comment]
Hi, I just published a new version on NPM. Can you please try it and give feedback on whether it is fixed or not?

**Comment by Jobians** [comment]
I will try it tomorrow and give you feedback

**Comment by butthx** [comment]
Hi, any update about latest version?

**Comment by Jobians** [comment]
@butthx sorry for no response, my iMac screen got damaged

**Comment by butthx** [comment]
> @butthx sorry for no response, my iMac screen got damaged 

It's okay, if the new version still didn't work, open this issue again and give new information.
